### ISSUE TITLE
Use the system keyring instead of python to store user credentials

### ISSUE THREAD

**Issue by IkelAtomig** [ProtonVPN/proton-vpn-gtk-app#8] opened 2023-11-10 13:21 UTC
Please use the system keyring such as Kwallet or Gnome keyring. It is annoying the app always ask for password on rebooting the system, I login to the app everytime. 

This was never a problem in the old app.

**Comment by Anonymous941** [comment] 2023-11-10 15:37
For me, it always prompts for a password to create a new keyring, so I think this is a very annoying bug

**Comment by IkelAtomig** [comment] 2023-11-11 02:40
Oh, I see. I don't know why. I am in Fedora 39, this also existed in Fedora 38. While using the system wallet, it was not a problem at all. I don't know why this route to store data.

**Comment by IkelAtomig** [comment] 2023-11-11 11:41
It is now far more annoying whenever the app is started it asks for password.

**Comment by IkelAtomig** [comment] 2023-11-11 11:44
> For me, it always prompts for a password to create a new keyring, so I think this is a very annoying bug

I don't what you mean by the keyring here. But it went too far and asking for a password whenever I open the app or close it and re-open it.

This exists in both Fedora 39 and 38. In the old app, It used the system's keyring. No problem was at all there. I don't get why use a external service to manage data when there is already one available.

**Comment by IkelAtomig** [comment] 2023-11-11 13:04
A temporary solution I found. You login when the app asks you to login. Then logout and relogin. After that, It shouldn't ask for credentials again.

This seemed to be what worked for me when this issue came in Fedora 38.

**Comment by Anonymous941** [comment] 2023-11-12 15:39
Copying my comment on #4:

The problem is that it requires logging in every time the app is quit:

1. I reboot the computer or quit the app
When this happens, the following is logged just before exiting:
```plain
2023-10-28T18:00:19.520283 | proton.vpn.app.gtk.widgets.headerbar.menu.menu:200 | INFO | UI.DIALOG:QUIT | Yes
2023-10-28T18:00:19.522838 | proton.vpn.connection.states:120 | WARNING | CONN:WARNING | DISCONNECTED state received unexpected event: Down
2023-10-28T18:00:19.523318 | proton.vpn.app.gtk.services.reconnector.reconnector:98 | INFO | VPN reconnector disabled.
2023-10-28T18:00:19.523518 | proton.vpn.app.gtk.services.refresher.client_config_refresher:76 | INFO | Client config refresher disabled.
2023-10-28T18:00:19.523672 | proton.vpn.app.gtk.services.refresher.server_list_refresher:81 | INFO | Server list refresher disabled.
2023-10-28T18:00:19.523811 | proton.vpn.app.gtk.services.refresher.vpn_data_refresher:141 | INFO | APP.VPN_DATA_REFRESHER:DISABLE | VPN data refresher service disabled.
2023-10-28T18:00:19.645674 | asyncio:1758 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<TCPConnector._resolve_host() running at /usr/lib/python3/dist-packages/aiohttp/connector.py:880> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.10/asyncio/futures.py:385, Task.task_wakeup()]> cb=[TCPConnector._create_direct_connection.<locals>.drop_exception() at /usr/lib/python3/dist-packages/aiohttp/connector.py:1157]>
```
2. I then restart the app
This line is logged only once, if I restart the app again without logging in, it doesn't appear:
```plain
2023-10-28T18:01:16.144833 | proton.vpn.connection.vpnconnector:185 | INFO | CONN:STATE_CHANGED | Disconnected (initial state)
```
3. The GNOME or KDE keyring prompts me for a password to create a new one, every time
4. I now must enter my Proton username and password again, and since this requires Internet, I have to disable the killswitch manually

**Comment by IkelAtomig** [comment] 2023-11-13 01:52
![Screenshot 8](https://github.com/ProtonVPN/proton-vpn-gtk-app/assets/101938856/80555c96-f317-4c91-8cbc-a72c6b188c94)

I don't know how this is related but it asks for VPN Credentials at time even when internet connection is solid.



> 4. I now must enter my Proton username and password again, and since this requires Internet, I have to disable the killswitch manually

Same happens for me. But I didn't check for logs.




> Apparently the app uses `org.freedesktop.secrets` to store Proton account data (username, access token, etc.), and I am able to use KWallet or KeePassXC for this purpose.
> 
> For VPN connection, it seems that `network-manager-applet` / `plasma-nm` is needed. On KDE, `plasma-nm` requires the use of KWallet for VPN credentials.

I am pretty sure. If you see the credentials in your keyring. It means it is the data stored by Old app. The new app now stores its data in python keyring.

**Comment by IkelAtomig** [comment] 2023-11-13 12:54
In Kwallet is it under Secret Service ?

**Comment by Anonymous941** [comment] 2023-11-19 23:00
Could this be a conflict between `gnome-keyring-daemon` and KWallet?  Try running:

```bash
sudo chmod -x /usr/bin/gnome-keyring-daemon
sudo killall gnome-keyring-daemon
```

And rebooting (I didn't need it but it can't hurt).  After doing this, I disabled KWallet's secret service integration and enabled KeePassXC's.  Then it finally stopped prompting me!

**Comment by calexandru2018** [comment] 2023-11-20 11:14
Hey all. As @antermin points out we currently only support Gnome-keyring as a backend for the keyring service. Actually if you take a close look at [python-proton-keyring-linux](https://github.com/ProtonVPN/python-proton-keyring-linux/blob/unstable/setup.py#L12) you can see that we depend on the [keyring](https://github.com/jaraco/keyring) package.

**Comment by IkelAtomig** [comment] 2023-11-21 04:26
@calexandru2018 I use Fedora 39 with KDE.

**Comment by Anonymous941** [comment] 2023-11-26 02:34
I have a theory.  The problem on one computer mysteriously appeared when I switched to zsh.

@IkelAtomig Are you using zsh?
@antermin @calexandru2018 Are you using bash?

**Comment by Anonymous941** [comment] 2023-11-26 16:48
Is it possible then that it adds an important environment variable to `.bashrc`, but not `.zshrc`?

**Comment by IkelAtomig** [comment] 2023-11-27 04:02
@Anonymous941 I have no idea about `.zsh`. In my home directory I see `.bashrc` only.

**Comment by IkelAtomig** [comment] 2023-11-28 03:44
@calexandru2018 - I don't get the problem with KWallet. It is already unlocked automatically at login.

**Comment by t0mii** [comment] 2024-01-24 22:16
If i set a password for my default keyring it works, if i set empty passwort for the keyring the app deletes the entry in the keyring everytime at launch. wtf

**Comment by Anonymous941** [comment] 2024-01-25 00:31
> If i set a password for my default keyring it works, if i set empty passwort for the keyring the app deletes the entry in the keyring everytime at launch. wtf

Is this the issue??  This actually might be

**Comment by mcwillzz** [comment] 2024-02-17 22:33
> If i set a password for my default keyring it works, if i set empty passwort for the keyring the app deletes the entry in the keyring everytime at launch. wtf

Having the same issue. Debian 12, with auto-login and no password on the user logging in. I set the password for the keyring to be blank, and it recreates the keyring on every reboot. If I set a password it is fine, but I do not want to have to log in to my server to enter a password if I decide to reboot it...

**Comment by calexandru2018** [comment] 2024-02-29 09:23
Hey all, could you please send issue reports through the app so we have some logs on this please ? I talked internally to our QA and we're a bit unsure why this is happening with gnome backend, it is expected with KDE as kwallet is a bit more tricky. Please refer to the following ticket: https://github.com/ProtonVPN/proton-vpn-gtk-app/issues/35

**Comment by mcwillzz** [comment] 2024-03-02 19:04
> Hey all, could you please send issue reports through the app so we have some logs on this please ? I talked internally to our QA and we're a bit unsure why this is happening with gnome backend (can't reproduce on our side on gnome backends), it is expected with KDE as kwallet is a bit more tricky. Please refer to this ticket in the submission: #35

Report sent through the app, thank you for investigating! I was having issues headless so I switched from an LXC to a true VM and installed Debian Gnome just to use the VPN... and then ran into all of this after that. In my case, getting the CLI working without desktop environment dependencies would be ideal.

**Comment by IkelAtomig** [comment] 2024-03-04 02:03
I prefer the config files right now because of this issue which is more stable.

**Comment by calexandru2018** [comment] 2024-03-12 15:50
Closing this and any further discussions should be on https://github.com/ProtonVPN/proton-vpn-gtk-app/issues/30

**Closed** 2024-03-12 15:51 UTC
