### ISSUE TITLE
Review PR? Keyring issue

### ISSUE THREAD

**Issue by Anonymous941** [ProtonVPN/proton-vpn-gtk-app#30] opened 2024-02-15 20:52 UTC
Hi,

I've submitted ProtonVPN/python-proton-keyring-linux#1 over a month ago, and was told by @calexandru2018 that it was being discussed internally.  Can I have some kind of update on this, even if it's been declined?  This has been a very frustrating bug that impacts all my computers constantly, and likely causes issues with others as well.  Again, **any response would be fine**, just please tell me some update.

**Comment by calexandru2018** [comment] 2024-02-16 11:37
Hey @Anonymous941 apologize for the delay, it was really hard these last months.

So going back to the keyring issue. From what we've identified this issue seems to occurs on systems that have KWallet installed by default and auto-login enabled. Due to this (and since it's working on well on Gnome-keyring) we won't be merging this commit since it's working well as is, and that this is mainly quirks caused by KWalletm, also it might have un-intended consequences where it already is working well. We eventually want to work on a dedicated backend for KDE that supports KWallet.

**Comment by Anonymous941** [comment] 2024-02-16 17:08
> Hey @Anonymous941 apologize for the delay, it was really hard these last months.

That's okay, thanks for responding! :)

> So going back to the keyring issue. From what we've identified this issue seems to occurs on systems that have KWallet installed by default and auto-login enabled. Due to this (and since it's working on well on Gnome-keyring) we won't be merging this commit since it's working well as is, and that this is mainly quirks caused by KWalletm, also it might have un-intended consequences where it already is working well. We eventually want to work on a dedicated backend for KDE that supports KWallet.

This also happens on my computers that use GNOME, and don't have KWallet installed, so it must be another issue unrelated to the PR then...

**Comment by calexandru2018** [comment] 2024-02-27 15:13
@Anonymous941 do you mind confirming if you have auto-login enabled in your gnome setups ?

**Comment by Anonymous941** [comment] 2024-02-28 16:06
@calexandru2018 In the wallet or generally?  I do have auto-login enabled for the user on all of my computers, but now one of them randomly doesn't have that issue (and it's running KDE and KWallet)  No idea what is different about it and it also has autologin enabled.

Also, Ungoogled Chromium stores things in the keyring, and ProtonVPN keeps deleting that too every time I reboot (there's just a blank keyring), so the issue must be causing that

**Comment by calexandru2018** [comment] 2024-02-28 16:16
KWallet is known not to play well with auto-login, but about gnome keyring I don't recall. Do you mind disabling auto-login in one of your gnome machines and see if the issue persists please ?
We're currently working on WG so we might not have enough time to look into this, but we'll give our best.

**Comment by e34rrsff** [comment] 2024-03-08 11:59
I got the same issue and have been trying to troubleshoot this. I did have auto-login enabled & am on Ubuntu 22.04 with GNOME.

These are the steps I've tried:
- de-authenticate all sessions from any logins
- check & reconfigure permissions for my ~/.gnupg folder
- delete the empty entry for proton-sso-accounts; with "[]" as the password, in seahorse
- disable auto-login and reboot then re-login
- set the keyring password to nothing so that it is unencrypted

Still, I get the same error "Your session is invalid. Please login to re-authenticate."

Appreciate your efforts

**Comment by calexandru2018** [comment] 2024-03-08 12:17
Hmm that is odd @e34rrsff , do you mind installing that in a VM ? I'd recommend using [Boxes](https://apps.gnome.org/Boxes/) which much quicker then any other software out there (on Linux that is). Because our QA has tried to replicate (and also personally me) and we couldn't recreate it.

**Comment by e34rrsff** [comment] 2024-03-09 04:25
No luck.

I tried 2 separate 22.04 VM installs; one configured with auto-login from the install & one without, just in case that somehow it affected anything.

Also tried a Fedora VM, since I recall a post mentioning that it worked for them on there, still doesn't work for me.

**Comment by e34rrsff** [comment] 2024-03-11 07:47
Really the only other thing I can think of is if somehow physical security keys affect logging in, if you can't reproduce the issue.

**Comment by calexandru2018** [comment] 2024-03-11 10:52
> Really the only other thing I can think of is if somehow physical security keys affect logging in, if you can't reproduce the issue.

Do you use physical security keys?

**Comment by Anonymous941** [comment] 2024-03-11 15:06
@calexandru2018 I don't use them, and still have this issue on many computers
Also I'll try to replicate this in a VM, @e34rrsff can you share the link to the ISO you're using?

**Comment by e34rrsff** [comment] 2024-03-11 20:05
> Do you use physical security keys?

I do
> @e34rrsff can you share the link to the ISO you're using?

I'm just using the normal ISOs from Ubuntu's and Fedora's websites

Ubuntu: https://releases.ubuntu.com/22.04.4/ubuntu-22.04.4-desktop-amd64.iso
Fedora: https://southfront.mm.fcix.net/fedora/linux/releases/39/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-39-1.5.iso

**Comment by e34rrsff** [comment] 2024-03-11 20:08
@Anonymous941 Well, how about 2FA codes?

**Comment by Anonymous941** [comment] 2024-03-12 14:44
> @Anonymous941 Well, how about 2FA codes?

No, just a securely generated password.  One thing that I think is important is that it deletes the _entire_ keyring and makes a new one, which removes other programs' keys too.  So this should narrow down the bug because it must be with code that deletes the keyring

**Comment by Anonymous941** [comment] 2024-03-12 16:27
Thank you so much for looking into this issue!  I have one computer that runs KWallet, and doesn't have this issue, plus another that also uses KWallet and prompts every time I reboot.  Two of them also don't work and use GNOME keyring + autologin.

Here are the results of running those commands on the computer that DOES work

Autologin enabled:

```plain
$ keyring --list-backends
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.libsecret.Keyring (priority: 4.8)
keyring.backends.SecretService.Keyring (priority: 5)
keyring.backends.kwallet.DBusKeyring (priority: 5.1)
keyring.backends.chainer.ChainerBackend (priority: 10)
$ keyring set test test
Password for 'test' in 'test': 
$ keyring get test test
test content
$ keyring del test test
```

Autologin disabled:

```plain
$ keyring --list-backends
keyring.backends.chainer.ChainerBackend (priority: 10)
keyring.backends.libsecret.Keyring (priority: 4.8)
keyring.backends.kwallet.DBusKeyring (priority: 5.1)
keyring.backends.SecretService.Keyring (priority: 5)
keyring.backends.fail.Keyring (priority: 0)
$ keyring set test test
Password for 'test' in 'test': 
$ keyring get test test
test content
$ keyring del test test
```

**Comment by calexandru2018** [comment] 2024-03-12 16:36
Just so it's clear to me, the above tests were run on which distros and with which default DE ?

**Comment by NigoriousT** [comment] 2024-03-13 07:42
I have done a bit more testing, happens on:
- Ubuntu 22.04, 23.10.1
- Kubuntu 22.04, 23.10
- Xubuntu 23.10 minimal
- Debian 12 Gnome
- Debian 12 KDE
Does not happen on:
- Fedora Workstation 38, 39
- Fedora Silverblue 38, 39 (unofficial flatpak)
- OpenSuse Tumbleweed Gnome (unofficial flatpak)
- OpenSuse MicroOS Gnome (unofficial flatpak)

@Anonymous941 You mentioned one of your computers don't have this issue, if you have distrohopped did that one specific computer continue working fine while all the others did not?

I am thinking there is a small possibility this issue happens on specific hardware because:
- The Proton employees likely have newer hardware at work and can't recreate this issue
- I have a 12 year old ivy bridge intel pentium that consistently has this issue
- Anon mentioned one of their computers does not have the issue

High performance processors may avoid this issue by doing something faster related to the keyring? Maybe if everyone posts their cpu we can find a pattern?

Its strange the Fedoras work for me, maybe they have a package which makes the keyring work different?

**Comment by calexandru2018** [comment] 2024-03-13 08:58
@NigoriousT I find it hard to believe that it's related to hardware. If you don't mind, could you test the same things I asked @Anonymous941 to test in my post above please ?

**Comment by Lintech-1** [comment] 2024-03-13 11:29
I use CachyOS and did the following to run protonvpn
```bash 
sudo vim /usr/share/dbus-1/services/org.freedesktop.secrets.service 
```
but still I have this output and the connections are not reproducible
```
2024-03-13T11:27:55.628144 | proton.keyring_linux.core.keyring_linux:111 | ERROR | Unexpected keyring "keyring.backends.SecretService.Keyring (priority: 5)" error
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/proton/keyring_linux/core/keyring_linux.py", line 99, in _is_backend_working
    keyring_backend.get_password(
  File "/usr/lib/python3.11/site-packages/keyring/backends/SecretService.py", line 78, in get_password
    collection = self.get_preferred_collection()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/keyring/backends/SecretService.py", line 61, in get_preferred_collection
    collection = secretstorage.get_default_collection(bus)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/secretstorage/collection.py", line 177, in get_default_collection
    return Collection(connection)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/secretstorage/collection.py", line 45, in __init__
    self._collection.get_property('Label')
  File "/usr/lib/python3.11/site-packages/secretstorage/util.py", line 67, in get_property
    (signature, value), = self.send_and_get_reply(msg)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/secretstorage/util.py", line 48, in send_and_get_reply
    raise DBusErrorResponse(resp_msg)
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.NameHasNoOwner] ('Could not activate remote peer: unit failed.',)
2024-03-13T11:27:55.773575 | proton.vpn.connection.vpnconnector:238 | INFO | CONN:STATE_CHANGED | Disconnected (initial state)
2024-03-13T11:27:55.774546 | proton.vpn.app.gtk.app:57 | INFO | APP:PROCESS_START | self=<app.App object at 0x76596217ee40 (proton+vpn+app+gtk+app+App at 0x18b3290)>
2024-03-13T11:27:55.834718 | proton.vpn.app.gtk.services.reconnector.reconnector:96 | INFO | VPN reconnector enabled.
2024-03-13T11:27:57.147895 | proton.vpn.app.gtk.controller:139 | INFO | APP.STARTUP:STARTUP_ACTIONS | Running startup actions
2024-03-13T11:27:57.148074 | proton.vpn.app.gtk.widgets.vpn.vpn_widget:178 | INFO | APP.VPN:WIDGET_READY | VPN widget is ready (load time: 1.32 seconds)
2024-03-13T11:27:57.148163 | proton.vpn.app.gtk.services.refresher.vpn_data_refresher:148 | INFO | APP.VPN_DATA_REFRESHER:ENABLE | VPN data refresher service enabled.
2024-03-13T11:27:57.148235 | proton.vpn.app.gtk.services.refresher.client_config_refresher:68 | INFO | Client config refresher enabled.
2024-03-13T11:27:57.148316 | proton.vpn.app.gtk.services.refresher.client_config_refresher:107 | INFO | Next client config refresh scheduled in 2:37:51.528084
2024-03-13T11:27:57.148368 | proton.vpn.app.gtk.services.refresher.server_list_refresher:74 | INFO | Server list refresher enabled.
2024-03-13T11:27:57.148886 | proton.vpn.session.utils:25 | INFO | API:REQUEST | '/vpn/loads'
2024-03-13T11:27:58.212924 | proton.vpn.app.gtk.services.reconnector.reconnector:176 | INFO | Network connectivity was detected.
```

**Comment by Anonymous941** [comment] 2024-03-13 14:39
> You mentioned one of your computers don't have this issue, if you have distrohopped did that one specific computer continue working fine while all the others did not?

It's a ThinkPad T470s, and what's strange it that it had the issue for months, then one day it just stopped and permanently stayed that way.  I'm using KUbuntu and haven't changed distros on that computer but have upgraded to 22.04 (I _think_ it was before that issue appeared).  I have no idea why

**Comment by Anonymous941** [comment] 2024-03-13 14:39
> Just so it's clear to me, the above tests were run on which distros and with which default DE (assume it's KDE but want to be sure) ?

@calexandru2018 KUbuntu, and I can run it on other computers that do have that issue if you want

**Comment by calexandru2018** [comment] 2024-03-13 15:15
> This is running Ubuntu, GNOME, GNOME wallet and has the issue.

So the one that has this keyring issue, didn't display any errors with the keyring commands above ? If so could you try setting an entry, reboot and then try to get it again to ensure it's being persisted to keyring please ?

**Comment by NigoriousT** [comment] 2024-03-14 00:57
@calexandru2018 Ubuntu 22.04, same result with auto login off and on:

d@d:~/Desktop$ keyring --list-backends
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.libsecret.Keyring (priority: 4.8)
keyring.backends.SecretService.Keyring (priority: 5)
keyring.backends.chainer.ChainerBackend (priority: 10)
d@d:~/Desktop$ keyring set test test
Password for 'test' in 'test': 
d@d:~/Desktop$ keyring get test test
d
d@d:~/Desktop$ keyring del test test
d@d:~/Desktop$ 

On Fedora Workstation 39, the only difference is this command returns the strings in a different order:

$ keyring --list-backends
keyring.backends.libsecret.Keyring (priority: 4.8)
keyring.backends.chainer.ChainerBackend (priority: 10)
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.SecretService.Keyring (priority: 5)

**Comment by NigoriousT** [comment] 2024-03-14 23:43
@calexandru2018 Ubuntu 22.04

$ keyring set test test
(enter "d")
$ reboot
$ keyring get test test 

brought up the same pop up as if I had opened protonvpn, and did not remember the key I set.

**Comment by calexandru2018** [comment] 2024-03-15 09:31
@NigoriousT the password you set was "d" in this case. But ok that at the least is some progress. It means that the keyring backend package that we rely on is not storing the data. Can you confirm me the following please:
- This test was done on which distro
- What DE
- Is auto-login enabled or not ?
- Are the any particularities about what you have installed ?

I'll try to replicate this again on my side to see what happens with the info you provided and comeback to you.

**Comment by NigoriousT** [comment] 2024-03-15 19:47
@calexandru2018 Its a clean Ubuntu 22.04 in Gnomeboxes with its default pre-customized gnome. I did not install literally anything except ProtonVPN as instructed by your website. I have tested both auto login settings once again and it happens on both.

**Comment by calexandru2018** [comment] 2024-03-19 08:48
@NigoriousT that is really odd. I just recently installed the latest 22.04.04 and tried it out in Gnome Boxes, this is what I did:

- Installed latest version
- Updated
- Installed Proton VPN
- ran `$ keyring set test test`
- entered `random pass`
- rebooted
-  ran `$ keyring get test test`
- got `random pass`


![Screenshot from 2024-03-19 08-44-47](https://github.com/ProtonVPN/proton-vpn-gtk-app/assets/31934100/7098e79d-1723-4f03-8570-8914814e42cb)
![Screenshot from 2024-03-19 08-45-42](https://github.com/ProtonVPN/proton-vpn-gtk-app/assets/31934100/10407707-86fa-4f9d-8c59-1fc8c5ed4410)
![Screenshot from 2024-03-19 08-45-52](https://github.com/ProtonVPN/proton-vpn-gtk-app/assets/31934100/956d7e54-e0f4-4493-be01-100ee7b047a5)

**Comment by NigoriousT** [comment] 2024-03-19 21:45
@calexandru2018 I think it's caused by the keyring password being blank. I usually install Ubuntu with auto login turned on in the graphical installer which im pretty sure causes the keyring password to be blank. I set the password to something not null and now it behaves as you describe right above.

**Comment by calexandru2018** [comment] 2024-03-20 11:22
Thanks for the feedback @NigoriousT , this has really helped us nail the the issue, and we found out what the possible issue is, and why the PR actually solves it (in certain limited scenarios like this).

- When someone installs the distribution and sets the auto-login option to true, Gnome-Keyring automatically creates a keyring in clear text (don't know why, but that's the default behaviour)
- When our backend attempts to transform the data to json upon reading, it fails because it can not convert new lines as @Anonymous941 has correctly pointed out
- The problem was that we couldn't understand in which case this was happening, but with your help we narrowed down the issue
- This is our conclusion: 
    - when a user has a keyring password set, the content in the keyring is automatically encrypted/decrypted when it is fetched by our backend, and thus we assume (because we couldn't find info that confirms this) that it automatically does this conversion of `\n` for us
    - when a user has no keyring password set, the content is stored in the keyring in cleartext and thus when our backend fetches it, the json decode fails because the `\n` are not correctly set, thus "crashing" and deleting the keyring entry due to the `try/except` clause

Now that we have a better understanding of how things works and what is happening, we'll be merging this PR as it fixes this edge case (and honestly it was hard to predict it). Once the packages with this commit is published we'll close this ticket.

NOTE: Be aware thought that if you have auto-login set, you'll always be prompted to unlock the keyring whenever you want to open the app for the first time after a reboot/logout or something similar. This is expected behavior from the keyring side because if you auto-login and have a password set you'll need to type your keyring password to unlock it.

**Comment by Anonymous941** [comment] 2024-03-20 16:17
I can't tell you how happy I am now that the issue has finally been found!  Thank you for fixing it, the Linux client is now finally usable!  Also, I want to clarify that @Wizzerinus is the one who actually found the bug, and I just made the PR

> After this fix, if you restart your machine you'll be logged out and prompted to set the password for they keyring because our app is requesting it. I've tested this and unfortunately this means that it won't be possible to have a no-password keyring.

How do other apps implement it?  This is going to be a problem for my computers that don't have a password at all, because I can't automatically unlock it with the login password

**Comment by calexandru2018** [comment] 2024-03-20 17:19
> I can't tell you how happy I am now that the issue has finally been found!  Thank you for fixing it, the Linux client is now finally usable!  Also, I want to clarify that @Wizzerinus is the one who actually found the bug, and I just made the PR

Gotcha thank you for mentioning it. The problem seems to be actually when the keyring stores (without password) and for some reason it's not storing in the json format that we're setting, so not sure if it's a bug of an underlying package that we use or just a bug of gnome keyring. But now at the least we've managed to reproduce.



> > After this fix, if you restart your machine you'll be logged out and prompted to set the password for they keyring because our app is requesting it. I've tested this and unfortunately this means that it won't be possible to have a no-password keyring.
> 
> 
> 
> How do other apps implement it?  This might be a problem for my computers that don't have a password at all, because I can't automatically unlock it with the login password.  I might be able to set some dummy password on the user and enable auto-login, but that seems to cause issues as noted above...

Other apps might be using sql databases, but this is just the default behavior of gnome keyring (kwallet does not even work with that feature IIRC)

**Comment by calexandru2018** [comment] 2024-04-04 11:49
So we've investigated this further and created a discussion with gnome to see if this could be fixed at gnome-keyring level or not, feel free to follow it: https://discourse.gnome.org/t/possible-bug-or-feature-storing-getting-data-keyring-protected-vs-unprotected-keyring/20312

**Comment by calexandru2018** [comment] 2024-04-08 10:11
So given this is a gnome-keyring bug, we'll release the fix to beta this week, though bear in mind, for the person that made the MR we won't be able to merge your MR locally into gitlab because the fix was done in the https://github.com/ProtonVPN/python-proton-keyring-linux-secretservice/ mainly because the issue is with gnome-keyring. We could at the least mention your name if that is ok with you in the commit @Wizzerinus

**Comment by Wizzerinus** [comment] 2024-04-08 10:45
Yeah sounds good o7

**Comment by calexandru2018** [comment] 2024-04-11 15:07
- https://repo.protonvpn.com/fedora-39-unstable/python3-proton-keyring-linux/python3-proton-keyring-linux-0.0.2-1.fc39.noarch.rpm
- https://repo.protonvpn.com/fedora-39-unstable/python3-proton-keyring-linux-secretservice/python3-proton-keyring-linux-secretservice-0.0.2-1.fc39.noarch.rpm

These two packages should solve the issue, please give them a try. If all goes well all updates go to stable next week.

**Comment by calexandru2018** [comment] 2024-04-15 09:51
The fixes are public:

- https://github.com/ProtonVPN/python-proton-keyring-linux/releases/tag/v0.0.2
- https://github.com/ProtonVPN/python-proton-keyring-linux-secretservice/releases/tag/v0.0.2

Feel free to close the ticket please, if not closed within ~30days I'll close it myself assuming that it was solved for everybody :)

I'll be closing the MR, thank you all 👍🏻

**Closed** 2024-04-15 14:33 UTC

**Comment by Cherkah** [comment] 2024-07-22 19:15
I use protonmail and protonvpn on archlinux KDE. As much as it is nice to use protonmail with thunderbird, it is less nice to use protonvnp with gnome-keyring.

The problem is that the option to choose the "secret-service" is absent unlike the vpn application.
The Key Chain is managed with kwallet (default). Which is obviously inconsistent. especially since both applications are created by the same company.
I consider this inconvenience to be a bug!!!

can you provide this feature

**Comment by Anonymous941** [comment] 2026-03-05 16:23
Update: this fix no longer works.

**Comment by Retalak** [comment] 2026-05-23 23:01
I am getting prompted for root password every time now on Arch with KDE.

**Comment by Anonymous941** [comment] 2026-05-24 23:30
@Retalak #100 has the active discussion of this issue
