### ISSUE TITLE
ProtonVPN App (from Proton repos) slow and unresponsive

### ISSUE THREAD

**Issue by pgerlatzek** [ProtonVPN/proton-vpn-gtk-app#50] opened 2024-05-06 11:57 UTC
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [X] I have searched open and closed issues for duplicates
- [X] This isn't a feature request
- [ ] This is not a report about my app not working as expected

----------------------------------------
System: Fedora 39, KDE Plasma 5.27.11, Wayland, Kernel 6.8.8-200 (should not be relevant but maybe there might be a difference on other systems)

The ProtonVPN GTK App (from Proton repos)  is on activation (on click if opened on desktop but out of focus, minimized in taskbar, or if minimized in tray) unresponsive and greyed (sometimes even whited) out. This has been the case across the last updates for the GTK app. The App works fine otherwise, just it takes some time to become fully responsive and to be displayed properly.

Other than that, thank you very much for making the GTK app, it works great otherwise.

That is basically all.

**Comment by calexandru2018** [comment] 2024-05-06 12:05
Hey @pgerlatzek, have you attempted to install the app directly from our repos and trying it that way ? Do note that the flatpak version is not officially supported and we can't really improve much on that front at this point.

**Comment by simonhammes** [comment] 2024-09-17 17:02
Same issue using `proton-vpn-gtk-app` on Debian. Today I upgraded to **4.4.5**, but the unresponsiveness persists.

<details><summary>Startup Logs</summary>
<p>

```
2024-09-17T16:57:29.829727 | proton.vpn.core.connection:419 | INFO | CONN:STATE_CHANGED | Disconnected (initial state)
2024-09-17T16:57:30.057433 | proton.vpn.app.gtk.app:57 | INFO | APP:PROCESS_START | self=<app.App object at 0x7f0f1d7947c0 (proton+vpn+app+gtk+app+App at 0x2a38210)>
2024-09-17T16:57:30.136124 | proton.vpn.app.gtk.services.reconnector.reconnector:97 | INFO | VPN reconnector enabled.
2024-09-17T16:57:33.508852 | proton.vpn.app.gtk.controller:144 | INFO | APP.STARTUP:STARTUP_ACTIONS | Running startup actions
2024-09-17T16:57:33.509041 | proton.vpn.app.gtk.widgets.vpn.vpn_widget:182 | INFO | APP.VPN:WIDGET_READY | VPN widget is ready (load time: 3.38 seconds)
2024-09-17T16:57:33.509148 | proton.vpn.app.gtk.services.refresher.vpn_data_refresher:176 | INFO | APP.VPN_DATA_REFRESHER:ENABLE | VPN data refresher service enabled.
2024-09-17T16:57:33.509223 | proton.vpn.app.gtk.services.refresher.client_config_refresher:70 | INFO | Client config refresher enabled.
2024-09-17T16:57:33.509327 | proton.vpn.app.gtk.services.refresher.client_config_refresher:109 | INFO | Next client config refresh scheduled in 2:35:12.316794
2024-09-17T16:57:33.509395 | proton.vpn.app.gtk.services.refresher.server_list_refresher:76 | INFO | Server list refresher enabled.
2024-09-17T16:57:33.509481 | proton.vpn.app.gtk.services.refresher.server_list_refresher:128 | INFO | Next server list refresh scheduled in 0:07:30.527284
2024-09-17T16:57:33.509548 | proton.vpn.app.gtk.services.refresher.certificate_refresher:71 | INFO | Certificate refresher enabled.
2024-09-17T16:57:33.510282 | proton.vpn.app.gtk.services.refresher.certificate_refresher:126 | INFO | Next certificate refresh scheduled in 3 days, 2:35:02.489765
2024-09-17T16:57:33.510368 | proton.vpn.app.gtk.services.refresher.feature_flags_refresher:70 | INFO | Features refresher enabled.
2024-09-17T16:57:33.510444 | proton.vpn.app.gtk.services.refresher.feature_flags_refresher:109 | INFO | Next features flags refresh scheduled in 1:53:26.340781
2024-09-17T16:57:36.850508 | proton.vpn.app.gtk.services.reconnector.reconnector:177 | INFO | Network connectivity was detected.
```

</p>
</details>

**Comment by Anonymous941** [comment] 2024-09-18 18:38
Also happening with `proton-vpn-gtk-app` on Ubuntu 24.04

**Comment by Anonymous941** [comment] 2024-10-09 00:20
@calexandru2018 Can you please reopen this?  It's affecting all of my computers running Ubuntu that use official Proton repos, with the exception of one high-end computer.  It's almost unusable on all the rest, every click causes it to stop responding for 10 seconds, so trying to do something like change a setting or even quit takes several minutes

**Comment by Anonymous941** [comment] 2024-10-10 15:56
Note that this hasn't always been the case, it's a bug introduced in newer versions

**Comment by Red6785** [comment] 2024-11-06 04:19
Please reopen. I also have this problem.

**Comment by calexandru2018** [comment] 2024-11-06 16:46
A fix for this is in the works. We've decreased the app startup memory consumption and also managed to speed app startup. A fix should be rolling out in the upcoming weeks, no exact date though, keep an eye on the release notes and ensure to be on the beta channel to get the latest updates.

**Comment by Anonymous941** [comment] 2024-11-06 19:20
@calexandru2018 Thanks for reopening the issue!  The problem is that the app is slow after starting, is that fix for startup specifically or does it fix this too?

**Comment by calexandru2018** [comment] 2024-11-07 11:58
So we've released today a "small" fix to beta. Basically reduces the app start-up from 300Mb or so to 75Mb. We've also redone the search widget and forced the server widgets to be lazy-loaded. You should expect a huge improvement on performance and app responsiveness. There is though a thing you'll have to do to have the latest version. After updating from the repo, you'll need to restart the app. If you logout/login you'll have to wait a couple of hours and then restart the app. We're aware of this and we'll improve this flow in the future.

**Comment by simonhammes** [comment] 2024-11-08 18:52
@calexandru2018 Thank you, performance with 4.7.2 (beta access enabled) on Ubuntu 24.04 is _so much_ better :rocket:

**Comment by calexandru2018** [comment] 2024-11-27 11:14
Given that this has been fixed and we've got confirmation from your side, i'll be closing this ticket.

**Closed by calexandru2018** 2024-11-27 11:14 UTC
