### ISSUE TITLE
ProtonVPN GTK High Memory Usage - 600Mb

### ISSUE THREAD

**Issue by idealemu** [ProtonVPN/proton-vpn-gtk-app#70] opened 2024-10-07 17:30 UTC
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

Hi,

I just noticed that the ProtonVPN GTK app was using 600 Mb of RAM on my system (Pop OS!), I have trouble seeing why the memory usage would be so high, especially since I did not notice such behaviour when using the previous ProtonVPN-cli community app. I know GTK can be memory hungry, but over half a gigabyte seems excessive.
I have restarted the app and the memory usage is now down to 400 Mb. This is still quite high but makes me wonder if there might be a memory leak somewhere; or technical reason as to why the app has such memory requirements.
The GTK app has a nice integration with my desktop environment, but if there is no fix or explanation for this, I might switch to another way of using protonvpn on Linux.
Best, IdealEmu

(RAM usage monitored with built-in Pop OS! resource monitor, htop, and glances)

**Comment by Anonymous941** [comment] 2024-10-09 00:21
Possibly related: #50 (which is incorrectly closed, the issue is still present)

**Comment by x11x** [comment] 2024-10-10 11:08
I am seeing around 400 MB (in Fedora 40 Silverblue, Gnome Shell 46, Wayland).
It does seem high.

There are a large number of entries in the list of servers -- maybe this is causing it? I wonder if they could be lazy-loaded or something (just speculating, I haven't checked the source to see if this could be the problem or not).

I think I am getting the sluggish UI from #50 too.

**Comment by qcoudeyr** [comment] 2024-10-20 12:06
From my Linux (Ubuntu 24.10 x64) I have around 400mb ram that is being used by the application and from what I can see using the memory maps, there is 322mb that are actually in the heap, the rest of the ram is being used by Linux libs and python. I see also that pulseaudiofx take 64mb for some reason. As the program is written in python, I think it's pretty normal to have such a huge amount of ram being used by the app.

**Comment by calexandru2018** [comment] 2024-11-07 11:59
Hey all, this has been finally improved. Please see my answer [here](https://github.com/ProtonVPN/proton-vpn-gtk-app/issues/50#issuecomment-2462054389). We've managed to lower from the initial footprint of 300Mb at app startup to 75Mb.

@qcoudeyr it was taking so much RAM because we were creating all server widgets at app load, meaning that over 2k widgets were being created. Now this is lazily loaded, and only once you open a country will the server widgets be displayed. We'll looking into other possible performances, once of them migrating to Gtk4.

**Comment by calexandru2018** [comment] 2024-11-27 11:01
I'm closing this ticket since we've addressed this.

**Closed by calexandru2018** 2024-11-27 11:01 UTC
