### ISSUE TITLE
Finally found the keyring problem

### ISSUE THREAD

**Issue by Anonymous941** [ProtonVPN/proton-vpn-gtk-app#16] opened 2023-11-29 19:36 UTC
![Many keyrings](https://github.com/ProtonVPN/proton-vpn-gtk-app/assets/36797492/674d4deb-44a4-49e3-afdd-1e82e8dc0ce7)
These are either blank, contain just the ProtonVPN login password, or contain that password and some VPN configurations.  This is on GNOME, so `kde-wallet` cannot be causing the issue.  Could it be caused because I also have keyrings named `Default keyring`?
It seems very likely that the issue is that it fails to detect the keyring named `Default`, and makes another one every single time the app is restarted.  This means you have to login after every reboot
This is happening on all of my computers, some with KDE and some with GNOME, and probably caused #8

**Comment by Anonymous941** [comment] 2023-11-29 19:44
Edit: it makes the login `proton-sso-accounts` permanently, and while running, the login `proton-sso-account-xxxxx`:

![Keyring screenshot](https://github.com/ProtonVPN/proton-vpn-gtk-app/assets/36797492/bae0bb54-cc1c-4cc1-802c-04fcd479e6b1)

The problem is the `proton-sso-account-xxxxx` is deleted every time the app is quit, causing you to have to re-login each time

**Comment by Wizzerinus** [comment] 2023-12-30 08:55
For anyone wondering, I found the possible cause of this bug. Note that this may be setup dependent and not fix the bug for every single user of this app. (This was also reported through the support system)

So, ProtonVPN includes a number of PEM-encoded certificates in their secret files. They look like this:
```pem
-----BEGIN PUBLIC KEY-----
SomeLongBase64String
MaybeAnotherOneHere
-----END PUBLIC KEY-----
```
As you can see, there are newline breaks within this certificate. So, when ProtonVPN saves this certificate into the keyring, it gets saved as is. Note that ProtonVPN uses json files to store their secrets, so they're actually saving something like this:
```json
{"ServerPublicKey": "-----BEGIN PUBLIC KEY-----\nSomeLongBase64String\nMaybeAnotherOneHere\n-----END PUBLIC KEY-----\n"}
```
When the app reads the secrets however, the `\n` sequences are magically transformed into `\n` *characters*, so the variable looks like this now:
```json
{"ServerPublicKey": "-----BEGIN PUBLIC KEY-----
SomeLongBase64String
MaybeAnotherOneHere
-----END PUBLIC KEY-----
"}
```

As you can see this is not a valid JSON file, the github's syntax highlighter also agrees. So, this cannot be parsed by the code, and then the following happens:

https://github.com/ProtonVPN/python-proton-keyring-linux/blob/5ff3c7f9a1a162836649502dd23c2fbe1f487d73/proton/keyring_linux/core/keyring_linux.py#L63

This code deletes the secret whenever parsing fails, creating this bug.

You can bugfix this yourself by editing your copy of `keyring_linux.py` to include something like `stored_data = stored_data.replace("\n", "\\n")` before parsing the data with JSON. (Again, not sure if this is the cause of the bug for everyone, because it depends on a lot of factors! Sorry if this does not work for you, but it did work for me which is why I'm sharing it.)

**Comment by Anonymous941** [comment] 2024-01-02 20:47
@Wizzerinus Thank you, this worked and I finally have a fix for this very annoying and persistent bug!

I've submitted a PR, and in the meantime it can manually be patched by copying [my fork's keyring_linux.py](https://github.com/ProtonVPN/python-proton-keyring-linux/blob/94c72cb85dcc52e9ce57b7a468cf0c26e70ff0cc/proton/keyring_linux/core/keyring_linux.py) to `/usr/lib/python3/dist-packages/proton/keyring_linux/core/keyring_linux.py`

**Comment by Anonymous941** [comment] 2024-01-02 20:48
I will leave this issue open until the PR is merger upstream, @calexandru2018 can you take a look at it?

**Comment by calexandru2018** [comment] 2024-01-03 12:05
Hey @Anonymous941 thanks for the PR (and thank you @Wizzerinus for taking your time in identifying and fixing the issue). I'll take this PR and discuss this internally with our team.

**Comment by Anonymous941** [comment] 2024-02-02 23:46
> Hey Anonymous941 thanks for the PR (and thank you Wizzerinus for taking your time in identifying and fixing the issue). I'll take this PR and discuss this internally with our team.

@calexandru2018 Any updates one month later?

**Comment by calexandru2018** [comment] 2024-03-12 15:52
Closing this and any further discussions should be on https://github.com/ProtonVPN/proton-vpn-gtk-app/issues/30

**Closed by calexandru2018** 2024-03-12 15:52 UTC

**Comment by TheSingular** [comment] 2026-03-05 07:24
I had the same problem and it turned out I just had to set a default keyring in the seahorse app by right clicking and selecting set as default.

Previously, ProtonVPN would ask me to create a keyring named "Default" every time I  booted the PC, then ask me to login, and store the login credentials in the new keyring. As I have KDE and therefore kde-wallet, gnome-keyring is probably a package that got installed with ProtonVPN, and wasn't set up properly. ProtonVPN fails to set the new keyring as the default keyring as well.

Now that I have set a keyring as the default keyring, it doesn't ask me to set up a new one or login again. It just works as it should
